// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./.cq/providers"

  provider "aws" {
    source  = ""
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=Cloudquery! DB.name=postgres port=5432"
  }
}

// All Provider Configurations

provider "aws" {
  configuration {
    // Optional. if you want to assume role to multiple account and fetch data from them
    //accounts "<YOUR ID>" {
    // Optional. Role ARN we want to assume when accessing this account
    // role_arn = <YOUR_ROLE_ARN>
    // }
    // Optional. by default assumes all regions
    // regions = ["us-east-1", "us-west-2"]
    // Optional. Enable AWS SDK debug logging.
    aws_debug = false
    // The maximum number of times that a request will be retried for failures. Defaults to 5 retry attempts.
    // max_retries = 5
    // The maximum back off delay between attempts. The backoff delays exponentially with a jitter based on the number of attempts. Defaults to 60 seconds.
    // max_backoff = 30 
  }

  resources = [
    "ec2.transit_gateways",
    "elbv2.load_balancers",
    "fsx.backups",
    "iam.saml_identity_providers",
    "lambda.functions",
    "apigateway.rest_apis",
    "apigatewayv2.vpc_links",
    "s3.buckets",
    "sns.subscriptions",
    "route53.health_checks",
    "lambda.layers",
    "ec2.byoip_cidrs",
    "ec2.security_groups",
    "rds.certificates",
    "rds.instances",
    "route53.hosted_zones",
    "cloudfront.cache_policies",
    "directconnect.gateways",
    "ec2.regional_config",
    "route53.traffic_policies",
    "iam.openid_connect_identity_providers",
    "kms.keys",
    "route53.reusable_delegation_sets",
    "ecs.clusters",
    "iam.groups",
    "iam.password_policies",
    "emr.clusters",
    "iam.accounts",
    "redshift.subnet_groups",
    "apigateway.api_keys",
    "apigatewayv2.apis",
    "apigatewayv2.domain_names",
    "elasticbeanstalk.environments",
    "redshift.clusters",
    "cloudtrail.trails",
    "ec2.subnets",
    "ecr.repositories",
    "autoscaling.launch_configurations",
    "ec2.vpc_peering_connections",
    "sns.topics",
    "apigateway.client_certificates",
    "ec2.network_acls",
    "elbv2.target_groups",
    "apigateway.vpc_links",
    "config.conformance_packs",
    "ec2.vpn_gateways",
    "iam.policies",
    "ec2.instances",
    "directconnect.virtual_interfaces",
    "eks.clusters",
    "elbv1.load_balancers",
    "apigateway.usage_plans",
    "cloudwatch.alarms",
    "config.configuration_recorders",
    "efs.filesystems",
    "iam.server_certificates",
    "organizations.accounts",
    "apigateway.domain_names",
    "ec2.flow_logs",
    "ec2.nat_gateways",
    "ec2.vpc_endpoints",
    "ec2.ebs_volumes",
    "accessanalyzer.analyzers",
    "ec2.internet_gateways",
    "ec2.route_tables",
    "ec2.images",
    "ec2.vpcs",
    "iam.users",
    "rds.clusters",
    "cloudwatchlogs.filters",
    "directconnect.virtual_gateways",
    "ec2.customer_gateways",
    "rds.db_subnet_groups",
    "cloudfront.distributions",
    "iam.roles",
    "iam.virtual_mfa_devices"
  ]
}
