// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./.cq/providers"

  provider "azure" {
    source  = ""
    version = "latest"
  }

  connection {
    dsn = "postgres://postgres:Cloudquery!@localhost:5432/postgres?sslmode=disable"
  }
}

// All Provider Configurations

provider "azure" {
  configuration {
    //  Optional. if you not specified, cloudquery tries to access all subscriptions available to tenant
    # subscriptions = ["<YOU_SUBSCRIPTION_ID_HERE" >]
  }
  resources = [
    "ad.applications",
    "ad.groups",
    "ad.service_principals",
    "ad.users",
    "authorization.role_assignments",
    "authorization.role_definitions",
    "compute.disks",
    "compute.virtual_machines",
    "container.managed_clusters",
    "keyvault.vaults",
    "monitor.activity_log_alerts",
    # "monitor.activity_logs",
    "monitor.diagnostic_settings",
    "monitor.log_profiles",
    "mysql.servers",
    "network.public_ip_addresses",
    "network.security_groups",
    "network.virtual_networks",
    "network.watchers",
    "postgresql.servers",
    "resources.groups",
    "resources.policy_assignments",
    "security.auto_provisioning_settings",
    "security.contacts",
    "security.pricings",
    "security.settings",
    "sql.servers",
    "storage.accounts",
    "subscription.subscriptions",
    "web.apps",
  ]
}
