// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./.cq/providers"

  provider "azure" {
    source  = ""
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=Cloudquery! DB.name=postgres port=5432"
  }
}

// All Provider Configurations

provider "azure" {
  configuration {
    //  Optional. if you not specified, cloudquery tries to access all subscriptions available to tenant
    # subscriptions = ["<YOU_SUBSCRIPTION_ID_HERE" >]
  }
  resources = [
    "sql.servers",
    "network.virtual_networks",
    "compute.disks",
    "resources.groups",
    "keyvault.vaults",
    "storage.accounts",
    "mysql.servers",
    "postgresql.servers"
  ]
}
