// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "."

  provider "gcp" {
    source  = ""
    version = "latest"
  }

  connection {
    dsn = "host=localhost user=postgres password=Cloudquery! DB.name=postgres port=5432"
  }
}

// All Provider Configurations

provider "gcp" {
  configuration {
    // Optional. Filter as described https://cloud.google.com/sdk/gcloud/reference/projects/list --filter
    // project_filter = ""
    // Optional. If not specified either using all projects accessible.
    // project_ids = [<CHANGE_THIS_TO_YOUR_PROJECT_ID>]
  }
  resources = [
    "compute.images",
    "compute.forwarding_rules",
    "iam.service_accounts",
    "compute.addresses",
    "compute.backend_services",
    "compute.disk_types",
    "iam.project_roles",
    "storage.buckets",
    "domains.registrations",
    "compute.networks",
    "compute.firewalls",
    "cloudfunctions.functions",
    "compute.vpn_gateways",
    "compute.subnetworks",
    "sql.instances",
    "crm.projects",
    "compute.instances",
    "compute.interconnects",
    "compute.ssl_certificates",
    "kms.keys",
    "compute.autoscalers",
    "compute.disks"
  ]
}
