// Configuration AutoGenerated by CloudQuery CLI
cloudquery {
  plugin_directory = "./.cq/providers"

  provider "gcp" {
    source  = ""
    version = "v0.4.6"
  }

  connection {
    dsn = "postgres://postgres:Cloudquery!@localhost:5432/postgres?sslmode=disable"
  }
}

// All Provider Configurations

provider "gcp" {
  configuration {
    // Optional. Filter as described https://cloud.google.com/sdk/gcloud/reference/projects/list --filter
    // project_filter = ""
    // Optional. If not specified either using all projects accessible.
    // project_ids = [<CHANGE_THIS_TO_YOUR_PROJECT_ID>]
  }
  resources = [
    "bigquery.datasets",
    "cloudfunctions.functions",
    "compute.addresses",
    "compute.autoscalers",
    "compute.backend_services",
    "compute.disk_types",
    "compute.disks",
    "compute.firewalls",
    "compute.forwarding_rules",
    "compute.images",
    "compute.instances",
    "compute.interconnects",
    "compute.networks",
    "compute.projects",
    "compute.ssl_certificates",
    "compute.ssl_policies",
    "compute.subnetworks",
    "compute.target_https_proxies",
    "compute.target_ssl_proxies",
    "compute.url_maps",
    "compute.vpn_gateways",
    "crm.projects",
    "dns.managed_zones",
    "dns.policies",
    "domains.registrations",
    "iam.project_roles",
    "iam.service_accounts",
    "kms.keys",
    "logging.metrics",
    "logging.sinks",
    "monitoring.alert_policies",
    "resource_manager.folders",
    "resource_manager.projects",
    "sql.instances",
    "storage.buckets",
  ]
}
